Add relay docker-compose
bosagora/dms-chain pull request #11
Opened 2023-08-25 00:24 UTC by TrustHenry

2023-08-25 00:29 UTC, MichaelKim20 requested changes
docker-compose.yml 에 다음도 추가해 주세요
    ports:
      - "3000:3000"

2023-08-25 00:31 UTC, MichaelKim20 commented on stop
> +fi
start 스크립트 에도 추가해 주세요

2023-08-25 00:44 UTC, TrustHenry commented on stop
> +fi
반영 했습니다.

2023-08-28 01:39 UTC, MichaelKim20 requested changes

2023-08-28 01:39 UTC, MichaelKim20 commented on agora/relay/docker-compose.yml
> +      TOKEN_CONTRACT_ADDRESS: "0xFDa3d1ff3C570c2f76c2157Ef7A8640A75794eD9"
릴레이에 사용될 비밀키도 등록될 수 있도록 해주세요

2023-08-28 02:27 UTC, MichaelKim20 approved these changes
LGTM

2023-08-28 04:05 UTC, merged